# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9043ccccc3b1be42d57f3f2d24431d1d8be2d2b9efefcecac01e1eaa263742489768e5a1faf9fbe543411c2823d31ee2ebab8869edbd063ebb9f267b92a8dcd3

test:
  secret_key_base: 52cbc388d23a254c18d5297c2366d874a27ef0376513e565a355e75033f32008f657033ccf57debe574c9f1726e8227635b20c2e316c3f0244138c598a52214b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
